# .gitlab-ci.yml
image: google/cloud-sdk:latest

stages:
  - deploy

variables:
  KUBECONFIG: "/root/.kube/config"
  GCP_PROJECT_ID: "$csproject-440119"
  CLUSTER_NAME: "cotrole-sondas2"  # Nome do seu cluster GKE
  CLUSTER_ZONE: "us-central1-a"     # Zona do seu cluster GKE
  GCP_SERVICE_ACCOUNT_KEY: $GCP_SERVICE_ACCOUNT_KEY

before_script:
  # Autentica no Google Cloud usando a chave da conta de serviço
  - echo $GCP_SERVICE_ACCOUNT_KEY | base64 -d > "$HOME/gcloud-service-key.json"
  - gcloud auth activate-service-account --key-file="$HOME/gcloud-service-key.json"
  - gcloud config set project $GCP_PROJECT_ID
  - gcloud config set compute/zone $GKE_ZONE
  - gcloud container clusters get-credentials $GKE_CLUSTER_NAME

deploy-mysql:
  stage: deploy
  script:
    # Aplica o PersistentVolumeClaim
    - kubectl apply -f mysql-pv-pvc.yml
    # Aplica o Deployment e Service do MySQL
    - kubectl apply -f controle-sondas-db-deploy.yml
