apiVersion: apps/v1
kind: Deployment
metadata:
  name: controle-sondas-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: controle-sondas-db
  template:
    metadata:
      labels:
        app: controle-sondas-db
    spec:
      containers:
        - name: controle-sondas-db
          image: mysql:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "controle-sondas"
            - name: MYSQL_USER
              value: "usuario"
            - name: MYSQL_PASSWORD
              value: "senha"
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: controle-sondas-db-service
spec:
  selector:
    app: controle-sondas-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
