
services:
  controle-sondas:
    image: controle-sondas:latest  # A imagem do seu aplicativo
    restart: always
    build:
      context: .  # Diretório onde está seu Dockerfile
    container_name: controle-sondas
    ports:
      - "8080:8080"  # Mapeie a porta que seu app utiliza  (ajuste conforme necessário)
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://controle-sondas-db:3306/controle-sondas # Nome do host é o nome do serviço do MySQL
      SPRING_DATASOURCE_USERNAME: usuario  # Usuário do MySQL
      SPRING_DATASOURCE_PASSWORD: senha  # Senha do MySQL
      SPRING_JPA_HIBERNATE_DDL_AUTO: update  # Configuração do JPA
      SPRING_JPA_SHOW_SQL: true  # Habilita o log SQL
    depends_on:
      controle-sondas-db:  # Garante que o banco de dados esteja em execução antes do app
       condition: service_healthy


  controle-sondas-db:  # Nome do serviço do banco de dados MySQL
    image: mysql:latest  # Imagem do MySQL
    restart: always
    container_name: CsDB
    environment:
      MYSQL_ROOT_PASSWORD: admin  # Senha do root do MySQL
      MYSQL_DATABASE: controle-sondas  # Nome do banco de dados
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
    ports:
      - "3306:3306"  # Mapeia a porta do MySQL
    volumes:
      - cs_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"  # Porta do Grafana UI
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Definindo senha para o Grafana



volumes:
  cs_data:
  grafana_data:
