services:
  mysql:
    container_name: 'sistema_sondas'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=sistema_sondas'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'